### ISSUE TITLE
Always get error message like: “…list index out of range” and can't control my purifier. Some days ago worked good.

### ISSUE THREAD

**Issue by spider7611** [betaboon/philips-airpurifier#34]
Have problem with my philips air purifier. Before it was worked good. Now I see the purifier state but can’t control it. Always get error message like: “…list index out of range”
When I want to turn off get this message:

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/philips_airpurifier/fan.py:347
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:33:23 (1 occurrences)
Last logged: 10:33:23

[139649848765552] list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/config/custom_components/philips_airpurifier/fan.py", line 347, in async_turn_off
    await self._client.set_control_value(PHILIPS_POWER, "0")
  File "/usr/local/lib/python3.8/site-packages/aioairctrl/coap/client.py", line 91, in set_control_value
    return await self.set_control_values(
  File "/usr/local/lib/python3.8/site-packages/aioairctrl/coap/client.py", line 115, in set_control_values
    response = await self._client_context.request(request).response
  File "/usr/local/lib/python3.8/site-packages/aiocoap/protocol.py", line 731, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.8/site-packages/aiocoap/protocol.py", line 756, in _run
    await protocol.find_remote_and_interface(app_request)
  File "/usr/local/lib/python3.8/site-packages/aiocoap/protocol.py", line 299, in find_remote_and_interface
    if await ri.fill_or_recognize_remote(message):
  File "/usr/local/lib/python3.8/site-packages/aiocoap/tokenmanager.py", line 192, in fill_or_recognize_remote
    return await self.token_interface.fill_or_recognize_remote(message)
  File "/usr/local/lib/python3.8/site-packages/aiocoap/messagemanager.py", line 330, in fill_or_recognize_remote
    remote = await self.message_interface.determine_remote(message)
  File "/usr/local/lib/python3.8/site-packages/aiocoap/transports/udp6.py", line 328, in determine_remote
    return UDP6EndpointAddress(addrinfo[0][-1], self)
IndexError: list index out of range`

**Comment by spider7611** [comment]
After the last HA update it is working again. ;)
